# Example: Deploying an EC2 instance
resource "aws_instance" "app_server" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t3.large"

  tags = {
    Name        = "srv-app-prod-01"
    Environment = "PROD"
  }
}

# Dynamically generate the 100% schema-compliant likpi.yaml
resource "local_file" "likpi_manifest" {
  content = templatefile("${path.module}/likpi.yaml.tftpl", {
    instance_name     = aws_instance.app_server.tags["Name"]
    description       = "Application Node generated by Terraform"
    environment       = aws_instance.app_server.tags["Environment"]
    ip_address        = aws_instance.app_server.private_ip
    unique_identifier = aws_instance.app_server.id
    serial_number     = "AWS-${aws_instance.app_server.id}"
    cpu_count         = "2" # Must be a string per schema.json
  })
  filename = "${path.module}/likpi.yaml"
}
